Modules/Destination/Http/routes.php
<?php

Route::group(['middleware' => ['web','admin'], 'as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Modules\Destination\Http\Controllers'], function()
{
    		/*
             * For DataTables
             */
            Route::post('destination/get', 'DestinationTableController')->name('destination.get');
            /*
             * User CRUD
             */
            Route::resource('destination', 'DestinationController');
});

Modules/Destination/Entities/Destination.php
<?php

namespace Modules\Destination\Entities;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Modules\Country\Entities\Country;
use App\Enums\Table;

class Destination extends Model
{
    use SoftDeletes;
	 /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = Table::DESTINATION;

    protected $fillable = ["id","country_id","name","name_mm","destination_image","video_url","is_active"];

    public function country()
    {
        return $this->hasOne(Country::class, 'id','country_id');
    }

    public function getStatusBadgeAttribute()
    {
        if ($this->is_active == 1) {
            return '<span class="badge badge-success">active</span>';
        }

        return "<span class='badge badge-danger'>".__('labels.general.inactive').'</span>';
    }
    
    public function getShowButtonAttribute()
    {
    	if(auth()->user()->can('view destination')){
        	return '<a href="'.route('admin.destination.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
        }
       	return '';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
    	if(auth()->user()->can('edit destination')){
        	return '<a href="'.route('admin.destination.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
        }
       	return '';
    }

     /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        if (auth()->user()->can('delete destination')) {
            return '<a href="'.route('admin.destination.destroy', $this).'" data-method="delete"
                 data-trans-button-cancel="'.__('buttons.general.cancel').'"
                 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                 data-trans-title="'.__('strings.backend.general.are_you_sure').'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'" class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
        }

        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
            return $this->getShowButtonAttribute().$this->getEditButtonAttribute().$this->getDeleteButtonAttribute();
    }
}

Modules/Destination/Http/Controllers/DestinationController.php
<?php

namespace Modules\Destination\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

use Modules\Destination\Entities\Destination;
use Modules\Destination\Http\Requests\ManageDestinationRequest;
use Modules\Destination\Http\Requests\CreateDestinationRequest;
use Modules\Destination\Http\Requests\UpdateDestinationRequest;
use Modules\Destination\Http\Requests\ShowDestinationRequest;
use Modules\Destination\Repositories\DestinationRepository;
use Modules\Country\Repositories\CountryRepository;

class DestinationController extends Controller
{
 /**
     * @var DestinationRepository
     * @var CategoryRepository
     */
    protected $destination;

    /**
     * @param DestinationRepository $destination
     */
    public function __construct(DestinationRepository $destination , CountryRepository $country)
    {
        $this->destination = $destination;
        $this->country = $country;
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('destination::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $countries = $this->country->where('is_active',1)->get();
        return view('destination::create',compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CreateDestinationRequest $request)
    {
        $input = $request->except('_token','_method');
        $image = uniqid('destination_image-').'.'.$request->destination_image->extension();

        $input['destination_image'] = \Storage::disk('uploads')->putFileAs('destination_image', $request->file('destination_image'),$image);
        $this->destination->create($input);
        return redirect()->route('admin.destination.index')->withFlashSuccess(trans('destination::alerts.backend.destination.created'));
    }

    /**
     * @param Destination              $destination
     * @param ManageDestinationRequest $request
     *
     * @return mixed
     */
    public function edit(Destination $destination, ManageDestinationRequest $request)
    {
        $countries = $this->country->where('is_active',1)->get();
        return view('destination::edit',compact('countries'))
            ->withDestination($destination);
    }

    /**
     * @param Destination              $destination
     * @param UpdateDestinationRequest $request
     *
     * @return mixed
     */
    public function update(Destination $destination, UpdateDestinationRequest $request)
    {
        $input = $request->except('_token','_method');
        if($request->destination_image) {
            \File::delete('uploads/'.$destination->destination_image);
            $image = uniqid('destination_image-').'.'.$request->destination_image->extension();
            $input['destination_image'] = \Storage::disk('uploads')->putFileAs('destination_image', $request->destination_image,$image);
        }

        $this->destination->updateById($destination->id,$input);

        return redirect()->route('admin.destination.index')->withFlashSuccess(trans('destination::alerts.backend.destination.updated'));
    }

    /**
     * @param Destination              $destination
     * @param ManageDestinationRequest $request
     *
     * @return mixed
     */
    public function show(Destination $destination, ShowDestinationRequest $request)
    {
        return view('destination::show')->withDestination($destination);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(Destination $destination)
    {
        $this->destination->deleteById($destination->id);

        return redirect()->route('admin.destination.index')->withFlashSuccess(trans('destination::alerts.backend.destination.deleted'));
    }
}

Modules/Destination/Http/Controllers/DestinationTableController.php
<?php

namespace Modules\Destination\Http\Controllers;

use Illuminate\Routing\Controller;
use DataTables;
use Modules\Destination\Repositories\DestinationRepository;
use Modules\Destination\Http\Requests\ManageDestinationRequest;

class DestinationTableController extends Controller
{
    /**
     * @var DestinationRepository
     */
    protected $destination;

    /**
     * @param DestinationRepository $destination
     */
    public function __construct(DestinationRepository $destination)
    {
        $this->destination = $destination;
    }

    /**
     * @param ManageDestinationRequest $request
     *
     * @return mixed
     */
    public function __invoke(ManageDestinationRequest $request)
    {
        return DataTables::of($this->destination->getForDataTable())
            ->editColumn('destination_image', function ($destination){
                return '<img style="width:100px;height:100px;" src="../uploads/'.$destination->destination_image.'">';
            })
            ->editColumn('country_id', function($destination)
            {
                return $destination->country->name;
            })
            ->addColumn('status', function ($route) {
                return $route->status_badge;
            })
            ->addColumn('actions', function ($destination) {
                return $destination->action_buttons;
            })
            ->rawColumns(['country_id','destination_image','status','actions'])
            ->make(true);
    }
}

Modules/Destination/Resources/views/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('destination::labels.backend.destination.management') . ' | ' . __('destination::labels.backend.destination.create'))

@section('breadcrumb-links')
    @include('destination::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->form('POST', route('admin.destination.store'))->attribute('enctype', 'multipart/form-data')->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('destination::labels.backend.destination.management') }}
                        <small class="text-muted">{{ __('destination::labels.backend.destination.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.country').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('country_id') }}

                        <div class="col-md-10">
                            <select name="country_id" class="form-control select2">
                                @foreach($countries as $country)
                                    <option value="{{$country->id}}"> {{$country->name}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.name').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.name_mm').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('name_mm') }}

                        <div class="col-md-10">
                            {{ html()->text('name_mm')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.name_mm'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.video_url').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('video_url') }}

                        <div class="col-md-10">
                            {{ html()->text('video_url')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.video_url'))}}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.destination_image').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('destination_image') }}

                        <div class="col-md-10">
                            {{ html()->file('destination_image')
                                ->class('form-control-file')
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('destination::labels.backend.destination.table.active'))->class('col-md-2 form-control-label')->for('active') }}

                        <div class="col-md-10">
                            <label class="switch switch-label switch-pill switch-primary">
                                {{ html()->checkbox('is_active', true)->class('switch-input') }}
                                <span class="switch-slider" data-checked="yes" data-unchecked="no"></span>
                            </label>
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.destination.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')
{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
$(function(){
    $(".select").select2({
        placeholder: 'Choose Country',
        width: '100%'
    });
})

</script>
@endpush

Modules/Destination/Resources/views/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('destination::labels.backend.destination.management') . ' | ' . __('destination::labels.backend.destination.edit'))

@section('breadcrumb-links')
    @include('destination::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->modelForm($destination, 'PATCH', route('admin.destination.update', $destination->id))->attribute('enctype', 'multipart/form-data')->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('destination::labels.backend.destination.management') }}
                        <small class="text-muted">{{ __('destination::labels.backend.destination.edit') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.country').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('country_id') }}

                        <div class="col-md-10">
                            <select name="country_id" class="form-control select2">
                                @foreach($countries as $country)
                                    <option value="{{$country->id}}" @if($country->id == $destination->country_id) selected @endif> {{$country->name}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.name'))->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.name_mm'))->class('col-md-2 form-control-label')->for('name_mm') }}

                        <div class="col-md-10">
                            {{ html()->text('name_mm')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.name_mm'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.video_url').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('video_url') }}

                        <div class="col-md-10">
                            {{ html()->text('video_url')
                                ->class('form-control')
                                ->placeholder(__('destination::labels.backend.destination.table.video_url'))}}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('destination::labels.backend.destination.table.destination_image').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('destination_image') }}
                        <div class="col-md-10">
                            @if($destination->destination_image)
                                <img src="{{asset('uploads/'.$destination->destination_image) }}" alt="" class="img-thumbnail" width="200px">
                            @endif
                            {{ html()->file('destination_image')
                                ->class('form-control-file')}}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('destination::labels.backend.destination.table.active'))->class('col-md-2 form-control-label')->for('active') }}

                        <div class="col-md-10">
                            <label class="switch switch-label switch-pill switch-primary">
                                @if($destination->is_active == 1)
                                    {{ html()->checkbox('is_active', true)->class('switch-input') }}
                                @else
                                    {{ html()->checkbox('is_active', false)->class('switch-input') }}
                                @endif
                                <span class="switch-slider" data-checked="yes" data-unchecked="no"></span>
                            </label>
                        </div><!--col-->
                    </div><!--form-group-->

                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.destination.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')
{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
$(function(){
    $(".select").select2({
        placeholder: 'Choose Country',
        width: '100%'
    });
})

</script>
@endpush

Modules/Destination/Resources/views/includes/breadcrumb-links.blade.php
<li class="breadcrumb-menu">
    <div class="btn-group" role="group" aria-label="Button group">
        <div class="dropdown">
            <a class="btn dropdown-toggle" href="#" role="button" id="breadcrumb-dropdown-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ __('destination::menus.backend.destination.main') }}</a>

            <div class="dropdown-menu" aria-labelledby="breadcrumb-dropdown-1">
                <a class="dropdown-item" href="{{ route('admin.destination.index') }}">{{ __('destination::menus.backend.destination.all') }}</a>
                @can('create destination')
                <a class="dropdown-item" href="{{ route('admin.destination.create') }}">{{ __('destination::menus.backend.destination.create') }}</a>
                @endcan
            </div>
        </div><!--dropdown-->

        <!--<a class="btn" href="#">Static Link</a>-->
    </div><!--btn-group-->
</li>

Modules/Destination/Resources/views/includes/header-buttons.blade.php
@can('create destination')
<div class="btn-toolbar float-right" role="toolbar" aria-label="Toolbar with button groups">
    <a href="{{ route('admin.destination.create') }}" class="btn btn-success ml-1" data-toggle="tooltip" title="{{ __('destination::menus.backend.destination.create') }}"><i class="fas fa-plus-circle"></i></a>
</div>
<!--btn-toolbar-->
@endcan

Modules/Destination/Resources/views/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('destination::labels.backend.destination.management'))

@section('breadcrumb-links')
    @include('destination::includes.breadcrumb-links')
@endsection

@push('after-styles')
    {{ style("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css") }}
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('destination::labels.backend.destination.management') }} <small class="text-muted">{{ __('destination::labels.backend.destination.list') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('destination::includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="destination-table" class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.id') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.country') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.name') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.name_mm') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.destination_image') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.active') }}</th>
                            <th>{{ __('destination::labels.backend.destination.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

@push('after-scripts')
    {{ script("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js") }}
    {{ script("js/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#destination-table').DataTable({
                serverSide: true,
                ajax: {
                    url: '{!! route("admin.destination.get") !!}',
                    type: 'post',
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                        else swal(xhr.responseJSON.message);
                    }
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'country_id', name: 'country_id'},
                    {data: 'name', name: 'name'},
                    {data: 'name_mm', name: 'name_mm'},
                    {data: 'destination_image', name: 'destination_image'},
                    {data: 'status', name: 'status'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500,
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    load_plugins();
                }
            });
        });
    </script>
@endpush

Modules/Destination/Resources/views/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('destination::labels.backend.destination.management'))

@section('breadcrumb-links')
    @include('destination::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('destination::labels.backend.destination.management') }}
                    <small class="text-muted">{{ __('destination::labels.backend.destination.show') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.country') }}</th>
                            <td>{{ $destination->country->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.name') }}</th>
                            <td>{{ $destination->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.name_mm') }}</th>
                            <td>{{ $destination->name_mm }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.video_url') }}</th>
                            <td>{{ $destination->video_url }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.destination_image') }}</th>
                            <td><img src="{{asset('uploads/'.$destination->destination_image) }}" alt="" class="img-thumbnail" width="200px"></td>
                        </tr>
                        <tr>
                            <th>{{ __('destination::labels.backend.destination.table.active') }}</th>
                            <td>
                                {!! $destination->status_badge !!}
                              
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>{{ __('destination::labels.backend.destination.table.created') }}:</strong> {{ $destination->updated_at->timezone(get_user_timezone()) }} ({{ $destination->created_at->diffForHumans() }}),
                    <strong>{{ __('destination::labels.backend.destination.table.last_updated') }}:</strong> {{ $destination->created_at->timezone(get_user_timezone()) }} ({{ $destination->updated_at->diffForHumans() }})
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection

@push('after-scripts')

<script>


</script>
@endpush